[package]
name = "image-inferencer"
version = "0.0.0"
authors = ["Saam Tehrani"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasi-nn = "0.1.0"
log = "0.4"
wasm-logger = "0.2"
env_logger = "0.10"