[package]
name = "inferencer"
authors = ["Saam Tehrani"]
edition = "2021"

[dependencies]
ndarray = "0.16.1"
wit-bindgen = { version = "0.42.1", features = ["macros"] }
wit-bindgen-rt = { version = "0.42.1", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[workspace]
