[package]
name = "dev_wasinn_nif"
version = "0.1.0"
edition = "2021"

[lib]
name = "dev_wasinn_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.36.1"
server = { version = "0.0.1", path = "../server" }
tokio = "1.45.0"
